// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlueGIml-5pZ17RkJkkpJEEw_3mSBPj1A',
    appId: '1:471918202322:web:509a5084ba14efb0538c0b',
    messagingSenderId: '471918202322',
    projectId: 'cardscanner-a13c1',
    authDomain: 'cardscanner-a13c1.firebaseapp.com',
    storageBucket: 'cardscanner-a13c1.appspot.com',
    measurementId: 'G-JNBH9XH17J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwMqXdq0nSHXrdDHlBKsnVmtvkIEV3jRE',
    appId: '1:471918202322:android:a8b6970b83e6a432538c0b',
    messagingSenderId: '471918202322',
    projectId: 'cardscanner-a13c1',
    storageBucket: 'cardscanner-a13c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4kg1DxUFHT3QcQBtGbR7yNvgb833RArc',
    appId: '1:471918202322:ios:ea72547902cd0492538c0b',
    messagingSenderId: '471918202322',
    projectId: 'cardscanner-a13c1',
    storageBucket: 'cardscanner-a13c1.appspot.com',
    iosClientId: '471918202322-7vlb8q6tdlj6eu1k84lu3171bo1cn3a8.apps.googleusercontent.com',
    iosBundleId: 'com.example.cardscanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4kg1DxUFHT3QcQBtGbR7yNvgb833RArc',
    appId: '1:471918202322:ios:ea72547902cd0492538c0b',
    messagingSenderId: '471918202322',
    projectId: 'cardscanner-a13c1',
    storageBucket: 'cardscanner-a13c1.appspot.com',
    iosClientId: '471918202322-7vlb8q6tdlj6eu1k84lu3171bo1cn3a8.apps.googleusercontent.com',
    iosBundleId: 'com.example.cardscanner',
  );
}
